//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdviserListWebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adviser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Adviser()
        {
            this.AdviserCertificates = new HashSet<AdviserCertificate>();
            this.AdviserCompanies = new HashSet<AdviserCompany>();
            this.AdviserHistories = new HashSet<AdviserHistory>();
            this.AdviserPhotoes = new HashSet<AdviserPhoto>();
            this.PromotionLocations = new HashSet<PromotionLocation>();
        }
    
        public System.Guid adviserId { get; set; }
        public string fullName { get; set; }
        public string displayName { get; set; }
        public string nric { get; set; }
        public Nullable<System.DateTime> dateOfBirth { get; set; }
        public string gender { get; set; }
        public string contactNumber { get; set; }
        public string email { get; set; }
        public string address { get; set; }
        public string aboutMeShort { get; set; }
        public string aboutMe { get; set; }
        public string creditCardNumber { get; set; }
        public Nullable<System.DateTime> creditCardExpire { get; set; }
        public Nullable<bool> recurringPaymentAgreementFlag { get; set; }
        public string password { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public Nullable<System.DateTime> updatedDate { get; set; }
        public Nullable<long> viewCountFromWeb { get; set; }
        public Nullable<long> viewCountFromApp { get; set; }
        public Nullable<bool> activeFlag { get; set; }
        public string rns { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdviserCertificate> AdviserCertificates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdviserCompany> AdviserCompanies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdviserHistory> AdviserHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdviserPhoto> AdviserPhotoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PromotionLocation> PromotionLocations { get; set; }
    }
}
