//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdviserListWebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Company()
        {
            this.AdviserCompanies = new HashSet<AdviserCompany>();
        }
    
        public System.Guid companyId { get; set; }
        public string companyName { get; set; }
        public string webAddress { get; set; }
        public string address { get; set; }
        public string phone { get; set; }
        public string logo { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public Nullable<bool> activeFlag { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdviserCompany> AdviserCompanies { get; set; }
    }
}
