//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdviserListWebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PromotionLocation
    {
        public System.Guid id { get; set; }
        public System.Guid adviserId { get; set; }
        public string locationAddress { get; set; }
        public Nullable<double> latitude { get; set; }
        public Nullable<double> longitude { get; set; }
        public Nullable<System.DateTime> effectiveDate { get; set; }
        public Nullable<System.DateTime> expireDate { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public string description { get; set; }
        public Nullable<bool> activeFlag { get; set; }
        public Nullable<System.TimeSpan> effectiveTime { get; set; }
        public Nullable<System.TimeSpan> expireTime { get; set; }
        public string name { get; set; }
        public Nullable<int> cityId { get; set; }
    
        public virtual Adviser Adviser { get; set; }
        public virtual City City { get; set; }
    }
}
